# Generated by Django 3.2.6 on 2024-03-02 15:45

import core.MyFileStorage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=core.MyFileStorage.MyFileStorage(), upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('nom', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('type', models.CharField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('code_couleur', models.ForeignKey(db_column='code_couleur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_couleur', to='core.couleur')),
            ],
            options={
                'unique_together': {('nom', 'code_couleur', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('postid', models.TextField(null=True, unique=True)),
                ('couture', models.CharField(default='', max_length=254)),
                ('code_couture', models.ForeignKey(db_column='code_couture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_couture', to='core.couleur')),
                ('marque', models.ForeignKey(default='notdefined', on_delete=django.db.models.deletion.CASCADE, to='core.marque')),
                ('panneau', models.ManyToManyField(blank=True, db_column='panneau', related_name='panneau', to='core.Matiere')),
                ('siege', models.ManyToManyField(blank=True, db_column='siege', related_name='siege', to='core.Matiere')),
                ('tableau', models.ManyToManyField(blank=True, db_column='tableau', related_name='tableau', to='core.Matiere')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='core.imagevoiture')),
                ('volant', models.ManyToManyField(blank=True, db_column='volant', related_name='volant', to='core.Matiere')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='imagevoiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.voiture'),
        ),
    ]
