# Generated by Django 3.2.6 on 2021-08-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
            ],
        ),
    ]
