# Generated by Django 3.2.6 on 2021-08-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_rename_image_voiture_imagevoiture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('nom', models.CharField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('couleur', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='voiture',
            name='marque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.marque'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.matiere'),
        ),
    ]
