# Generated by Django 3.2.6 on 2021-08-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20210820_1520'),
    ]

    operations = [
    ]
