# Generated by Django 3.2.6 on 2021-08-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_alter_voiture_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='matiere',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='display.matiere'),
        ),
    ]
