# Generated by Django 3.2.6 on 2021-08-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20210820_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
