# Generated by Django 3.2.6 on 2021-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_alter_matiere_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='matiere',
        ),
        migrations.AddField(
            model_name='voiture',
            name='matiere',
            field=models.ManyToManyField(to='display.Matiere'),
        ),
    ]
