# Generated by Django 3.2.6 on 2021-08-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_auto_20210821_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='matiere',
        ),
        migrations.AddField(
            model_name='marque',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='couture',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='voiture',
            name='panneau',
            field=models.ForeignKey(db_column='panneau', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panneau', to='display.matiere'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='siege',
            field=models.ForeignKey(db_column='siege', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siege', to='display.matiere'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='tableau',
            field=models.ForeignKey(db_column='tableau', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableau', to='display.matiere'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='volant',
            field=models.ForeignKey(db_column='volant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volant', to='display.matiere'),
        ),
    ]
