# Generated by Django 3.2.6 on 2021-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20210825_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='siege',
        ),
        migrations.AddField(
            model_name='voiture',
            name='siege',
            field=models.ManyToManyField(blank=True, to='display.Matiere'),
        ),
    ]
