# Generated by Django 3.2.6 on 2021-08-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_auto_20210828_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='type',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='panneau',
        ),
        migrations.AddField(
            model_name='voiture',
            name='panneau',
            field=models.ManyToManyField(blank=True, db_column='panneau', related_name='panneau', to='display.Matiere'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='siege',
            field=models.ManyToManyField(blank=True, db_column='siege', related_name='siege', to='display.Matiere'),
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='tableau',
        ),
        migrations.AddField(
            model_name='voiture',
            name='tableau',
            field=models.ManyToManyField(blank=True, db_column='tableau', related_name='tableau', to='display.Matiere'),
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='volant',
        ),
        migrations.AddField(
            model_name='voiture',
            name='volant',
            field=models.ManyToManyField(blank=True, db_column='volant', related_name='volant', to='display.Matiere'),
        ),
    ]
