# Generated by Django 3.2.6 on 2021-08-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_auto_20210828_1309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'couleur', 'type')},
        ),
    ]
