# Generated by Django 3.2.6 on 2021-08-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_alter_matiere_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='description',
        ),
    ]
