# Generated by Django 3.2.6 on 2021-09-01 12:58

import display.MyFileStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0014_remove_voiture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagevoiture',
            name='image',
            field=models.FileField(storage=display.MyFileStorage.MyFileStorage(), upload_to='images/'),
        ),
    ]
