# Generated by Django 3.2.6 on 2021-09-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0016_auto_20210906_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='voiture',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='matiere',
            name='code_couleur',
            field=models.ForeignKey(db_column='code_couleur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_couleur', to='display.couleur'),
        ),
    ]
