# Generated by Django 3.2.6 on 2022-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0022_alter_voiture_marque'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'code_couleur', 'type')},
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='couleur',
        ),
    ]
